[package]
name = "clashrup"
description = "Simple CLI to manage your systemd clash.service and config subscriptions on Linux."
version = "0.2.7"
edition = "2021"
readme = "README.md"
license = "MIT"
authors = ["spencerwooo <spencer.woo@outlook.com>"]
homepage = "https://github.com/spencerwooo/clashrup"
repository = "https://github.com/spencerwooo/clashrup"
keywords = ["cli", "clash", "network", "linux"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
clap_complete = "4.1.4"
colored = "2.0.0"
serde = { version = "1.0.156", features = ["derive"] }
toml = "0.7.3"
flate2 = "1.0"
shellexpand = "3.0.0"
openssl = { version = "0.10", features = ["vendored"] }
serde_yaml = "0.9.17"
local-ip-address = "0.5.1"
reqwest = { version = "0.11", features = ["stream"] }
futures-util = "0.3"
indicatif = "0.17"
tokio = { version = "1.26", features = ["full"] }
truncatable = "0.1.3"
